version: "3.7"

services:
  db_go:
    image: postgres:14
    container_name: db_go
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
