@url = http://localhost:3333

## GET

GET {{url}}/users?limit=20 HTTP/1.1
Content-Type: application/json

### POST

POST {{url}}/users HTTP/1.1
Content-Type: application/json

{
  "senha": "1234",
  "email": "vineboneto@gmail.com",
  "firstName": "Vinicius",
  "lastName": "Boneto"
}