@url = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk3ODAyODgsInN1YiI6IjEwMDEifQ.ooUaeY0sLvSv3xhPrzJMBPjEih577tQ050cW7MEbObQ

## AUTH
POST {{url}}/account/login HTTP/1.1
Content-Type: application/json

{
  "email": "vineboneto@gmail.com",
  "senha": "1234"
}


### GET
GET {{url}}/account?limit=5&id=1001 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET SELF
GET {{url}}/account/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### POST
POST {{url}}/account HTTP/1.1
Content-Type: application/json

{
  "senha": "1234",
  "email": "vineboneto@gmail.com",
  "firstName": "Vinicius",
  "lastName": "Boneto"
}

### DELETE
DELETE {{url}}/account HTTP/1.1
Content-Type: application/json

{
  "id": 1
}